---
- name: Listen for rocketchat webhook
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: rocketchat webhook
      condition: event.payload is defined
      action:
        run_job_template:
          name: "chatops-action"
          organization: Default
